"""Testi della scheda DPG-SET-H2O rev. 02 in italiano, francese e inglese.

Le versioni FR ed EN usano dati europei (direttiva, gare ricambi in UK e Portogallo) al posto di
quelli solo italiani (PNRR, procedure d'infrazione). Fonti: ricerca/H2O_PP_dossier.md
"""

IT = {
    "html_lang": "it", "code": "IT", "file": "DPG_Settore_H2O_IT",
    "sheet": "Scheda settore", "rev": "REV. 02 · BOZZA",
    "tb": ("Documento", "Revisione", "Lingua", "Editore", "Pagina"),
    # ---------------------------------------------------------------- p1
    "eyebrow1": "Acque reflue, acqua industriale, acquacoltura",
    "h1": ("Griglie, filtri e ricambi", "in polipropilene, senza stampo"), "h1_size": "35pt",
    "lead": "Pannelli forati, elementi di griglia, ugelli, crepine e i pezzi in plastica che il costruttore non fa più: "
            "in <strong>polipropilene sinterizzato</strong>, dal disegno o dal pezzo vecchio, da uno a qualche migliaio. "
            "Il materiale che la depurazione usa da sempre, con una geometria che lo stampo non permette.",
    "kpis": [("≥ 2", "mm", "luce di passaggio, fori e fessure"), ("≤ 30", "cm", "pezzo singolo, oltre a moduli"),
             ("0", "stampi", "dal pezzo unico alla serie")],
    "fig1": "Pannelli di griglia a nastro, vista isometrica",
    "legend1": "Moduli forati agganciati al telaio inox della griglia. In azzurro: l'acqua",
    "key_red": "<b>In rosso</b>: le parti che si producono in additive",
    # ---------------------------------------------------------------- p2
    "p2_head": "Trattamento acque reflue e acqua industriale",
    "s01": "Perché adesso",
    "stats": [
        ("2024/3019", "Direttiva UE acque reflue urbane",
         "Recepimento entro luglio 2027. Trattamento dei microinquinanti obbligatorio sopra 150.000 AE: "
         "20% degli impianti entro il 2033, 60% entro il 2039, tutti entro il 2045."),
        ("600 M€", "PNRR, fognatura e depurazione",
         "Investimento 4.4 della missione M2C4: impianti nuovi e adeguati, e con loro griglie, filtri e ricambi."),
        ("4", "Procedure d'infrazione UE all'Italia",
         "Agglomerati non conformi e un parco impianti in buona parte vecchio: il ricambio fuori produzione è la norma."),
    ],
    "s02": "Il conto che conoscete",
    "was_k": "Come va oggi",
    "was": "Il pannello della griglia si ordina al costruttore e arriva in settimane, se il modello è ancora a catalogo. "
           "L'ugello del filtro è di una marca che non esiste più. La crepina è un assieme incollato che perde dove non "
           "deve, e la lamiera forata in inox pesa, costa e per una variante piccola chiede comunque un'attrezzatura.",
    "now_k": "In sinterizzazione",
    "now": "Il pezzo vecchio diventa un file con la sua revisione, e il file un lotto: da un pezzo a qualche migliaio, "
           "senza stampo. Telaio, clip, nervature e filetto nascono nello stesso pezzo. Il foro può allargarsi verso "
           "l'uscita e non trattenere, e la volta dopo il riordino è identico.",
    "s03": "Il polipropilene stampato è già in impianto", "s03_note": "Fonti pubbliche, in fondo alla pagina",
    "evidence": [
        ("Gestore idrico, Regno Unito", "United Utilities",
         "Nel programma Printfrastructure, finanziato dall'Ofwat, usa ogni giorno pezzi polimerici stampati: ugelli di "
         "lavaggio, canaline per strumenti e ricambi fuori produzione per i bracci dei filtri."),
        ("Costruttore di griglie", "Johnson Screens",
         "Ha portato in polipropilene stampato gli elementi del nastro filtrante di una griglia d'ingresso per reflui, "
         "al posto dell'acciaio inox."),
        ("Gestore idrico, Regno Unito", "Anglian Water",
         "Il primo pezzo che ha provato a stampare, con l'Università di Sheffield, è stato un ugello filtrante."),
        ("Ricerca, 2026", "Supporti MBBR in PP",
         "Supporti per biofilm a geometria gyroid stampati in PP, provati su refluo domestico in impianto pilota "
         "(Processes, 2026)."),
    ],
    "case_k": "In produzione, oggi",
    "case": "Per un gruppo internazionale del trattamento acque produciamo in serie ricorrente <strong>pannelli filtranti "
            "in polipropilene sinterizzato con luce da 2 mm</strong>: riordino a magazzino digitale, lotto tracciato. "
            "<strong>Non un prototipo: una fornitura.</strong>",
    "why_k": "Perché polipropilene",
    "why": "Non assorbe acqua e non idrolizza, come fa invece la poliammide. Regge acidi e basi diluiti, soda, cloruro "
           "ferrico e la chimica di lavaggio. Galleggia (circa 0,9 g/cm³) e pesa circa un ottavo dell'inox. "
           "È il materiale che vasche, tubi e ugelli usano da sempre.",
    "fonti_k": "Fonti",
    "fonti": [
        "Direttiva (UE) 2024/3019, eur-lex.europa.eu",
        "MASE, PNRR M2C4 inv. 4.4, mase.gov.it",
        "United Utilities, «Printfrastructure», unitedutilities.com",
        "Johnson Screens e HP, johnsonscreens.com; 3dprint.com, 2022",
        "Anglian Water e Univ. di Sheffield, 3dprint.com, 2015",
        "Processes 14(6):1001, 2026, doi 10.3390/pr14061001",
        "Stratasys, SAF PP: scheda materiale e white paper sulla tenuta",
        "Resistenza chimica del PP: Braskem, INEOS, Charlotte Pipe",
    ],
    # ---------------------------------------------------------------- p3
    "p3_head": "Dove entriamo nell'impianto",
    "eyebrow3": "Mappa dell'impianto",
    "h2_map": "Dalla griglia ai fanghi: dieci punti dove il pezzo in PP stampato ha senso",
    "fig2": "Schema di un impianto a fanghi attivi",
    "legend3": "In azzurro l'acqua, tratteggiata l'aria e la linea fanghi. Adatto: alto = pezzo già in plastica, specifico, con ricambio difficile",
    "key3": "<b>In rosso</b>: dove entra il PP stampato",
    "fit": {"A": "alto", "M": "medio"},
    "map": [
        ("Pannelli ed elementi di griglia", "Griglie a nastro, a pettine, rotostacci: pannelli forati da 2 mm, elementi, guide, pattini, portaspazzole.", "A"),
        ("Minuterie dei raschiatori", "Distanziali, blocchi di riempimento, punte dei raschia-schiume, staffe di regolazione degli stramazzi.", "A"),
        ("Dosaggio chimico", "Miscelatori statici piccoli, filtri di fondo, punte d'iniezione per cloruro ferrico e ipoclorito, a bassa pressione.", "M"),
        ("Aerazione", "Selle, anelli, adattatori e raccordi per griglie di diffusori fuori produzione. Il diffusore resta di serie.", "M"),
        ("Griglie di ritenzione MBBR", "Moduli con fessure da 4–5 mm e profilo anti-incastro, per impianti piccoli, industriali, pilota.", "A"),
        ("Supporti sonde", "Gabbie, portasonde a pendolo, cuffie con ugello d'aria di pulizia ricavato nel pezzo.", "A"),
        ("Ugelli e crepine", "Seconda fonte per modelli fuori catalogo: biofiltri, drenaggi, scambio ionico. Fessura da 2 mm.", "A"),
        ("Deodorizzazione", "Distributori di liquido e collettori con gli ugelli nello stesso pezzo, supporti, separatori di gocce.", "M"),
        ("Linea fanghi", "Portaugelli di lavaggio, supporti delle lame, deviatori di nastropresse e ispessitori.", "M"),
        ("Strumentazione", "Pozzetti di calma, filtri del campionatore, supporti lungo tutto l'impianto.", "A"),
    ],
    "off_k": "Fuori campo, e ve lo diciamo prima",
    "off": ["contatto con ozono e biossido di cloro", "giranti e centrifughe", "deflettori e stramazzi grandi in vetroresina",
            "supporti MBBR e riempimenti di serie", "fessure fini dei filtri a sabbia, sotto 2 mm", "zone Atex del biogas"],
    # ---------------------------------------------------------------- p4
    "p4_head": "Tre porte d'ingresso",
    "d1_small": "Per gestori, manutentori, chi fa service sulle griglie",
    "d1_h": "Il ricambio in plastica che non si trova più.",
    "d1_lead": "Pannelli, elementi e guide di griglie a nastro e a pettine, rotostacci e tamisadores, coperture, pattini, "
               "portaspazzole e portaugelli: li rifacciamo in PP dal pezzo vecchio, anche per macchine fuori produzione e "
               "anche un pezzo solo. Per chi fa service su più marche siamo il fornitore dei pezzi che il costruttore non "
               "dà più, o dà in settimane.",
    "steps": [("old", "Il pezzo vecchio", "o il disegno, o lo STEP. Anche rotto, anche di una marca che non c'è più."),
              ("scan", "Rilievo 3D", "misuriamo il pezzo e ricostruiamo quote, filetti e accoppiamenti."),
              ("file", "File con revisione", "il ricambio diventa un codice vostro, con la sua revisione."),
              ("batch", "Lotto in PP", "da un pezzo a qualche migliaio, tracciato, senza stampo."),
              ("again", "Riordino identico", "tra un anno o tra dieci, dal file, senza scaffale.")],
    "d2_small": "Per costruttori di griglie, rotostacci e filtri",
    "d2_h": "Il pannello forato in plastica, al posto della lamiera.",
    "fig3": "Sezione del pannello",
    "fig3_cap": "Nella lamiera il foro è dritto. Stampato, può allargarsi verso l'uscita come un profilo a cuneo: quello che entra, passa.",
    "fig4": "Superficie aperta, fori da 2 mm a quinconce",
    "fig4_cap": "Calcolo geometrico. Il setto minimo si fissa con voi, sulla rigidezza che serve al pannello.",
    "cmp_head": ("Lamiera inox forata", "Pannello stampato a iniezione", "PP sinterizzato"),
    "cmp": [("Attrezzatura", "punzonatura o laser", "uno stampo per ogni formato", "nessuna: il file"),
            ("Lotto che ha senso", "da un pezzo", "migliaia", "da un pezzo a qualche migliaio"),
            ("Forma del foro", "dritto", "quella che si sforma", "dritta, conica, diversa per zona"),
            ("Telaio e clip", "saldati o avvitati", "nello stampo", "nel pezzo, anche per un ricambio solo"),
            ("Peso", "7,9 g/cm³", "leggero", "circa 0,9 g/cm³"),
            ("Cloruri, acqua di mare", "l'inox li soffre", "nessun problema", "nessun problema"),
            ("Sabbia e grit", "buona", "ottima in poliuretano", "media: a valle della dissabbiatura"),
            ("Luce minima", "sotto il millimetro", "fine", "2 mm")],
    "ticks4": [("Telaio, nervature, clip e sede della guarnizione", " nello stesso pezzo: il modulo si aggancia e si cambia da solo."),
               ("Luce diversa per zona", " sullo stesso pannello, e codice del pezzo inciso sul telaio."),
               ("Un ottavo del peso dell'inox", ": il cambio pannelli si fa a mano, senza paranco."),
               ("Moduli fino a 30 cm", " di lato. Oltre, il pannello si divide in moduli che si agganciano, come i pannelli in poliuretano delle vagliatrici."),
               ("Dove non va", ": sabbia e grit prima della dissabbiatura consumano il PP più di poliuretano e UHMW; sotto 2 mm restano wedge-wire e tela.")],
    # ---------------------------------------------------------------- p5
    "p5_head": "Tre porte d'ingresso, e oltre",
    "d3_small": "Per chi produce, vende o monta ugelli e crepine",
    "d3_h": "Ugelli e crepine: la seconda fonte.",
    "fig5": "Crepina di controlavaggio: corpo, slot e filetto in un pezzo. A destra, sezione A-A.",
    "nz_p": "Il modello fuori catalogo, la marca che non esiste più, la variante per un solo impianto: la facciamo in PP, "
            "dal pezzo o dal disegno, con la stessa filettatura.",
    "ticks5": [("Corpo, slot e filetto in un pezzo", ": nessun incollaggio, nessuna giunzione che perde."),
               ("Profilo dello slot a cuneo", " verso l'interno: si pulisce al controlavaggio."),
               ("Il foro dell'aria di lavaggio", " nel gambo, nello stesso pezzo, se il vostro ugello lo prevede."),
               ("Fessura da 2 mm in su", ": biofiltri, drenaggi su ghiaia, scambio ionico, acquacoltura. Per la sabbia fine "
                "stampiamo il corpo e il cappello fessurato resta a catalogo.")],
    "s04": "Idee oltre la griglia", "s04_note": "Dove lo stesso PP lavora già", "lim": "limite",
    "ideas": [
        ("Supporti sonde autopulenti", "Tutti gli impianti", "Gabbie e cuffie per sonde di ossigeno, pH e torbidità con il canale dell'aria di pulizia dentro il pezzo.", "carichi bassi, pezzi specifici"),
        ("Griglie di ritenzione MBBR", "Impianti compatti, industria, pilota", "Moduli piani al posto del cilindro in wedge-wire inox, con fessure da 4–5 mm e profilo che non incastra il supporto.", "impianti grandi: a moduli"),
        ("Distributori per scrubber", "Deodorizzazione", "Distributore di liquido e ugelli in un pezzo solo, senza saldature, nella chimica di lavaggio del PP: soda, ipoclorito, acido solforico.", "separatori grandi: a moduli"),
        ("Ricambi di filtri a dischi e a tamburo", "Terziario, acquacoltura", "Ugelli e barre di lavaggio, pattini di aspirazione, telai dei pannelli: la tela resta tela, il supporto si stampa.", "la tela sotto 2 mm non si stampa"),
        ("Acquacoltura a ricircolo", "RAS, avannotterie", "Griglie di scarico delle vasche con luce per taglia di pesce, piastre di distribuzione dei degasatori, porta-ugelli. In acqua di mare l'inox soffre, il PP no.", "UV all'aperto da valutare"),
        ("Galvanica e acque industriali", "Pretrattamento", "Spruzzatori, miscelatori e interni delle vasche di neutralizzazione, dove il PP è già il materiale di casa.", "no solventi aromatici e clorurati"),
        ("Torri di raffreddamento", "Acqua di processo", "Ugelli di spruzzo e adattatori per torri i cui ricambi non si trovano più, con l'orifizio che serve.", "sopra circa 60 °C da valutare"),
        ("Industria alimentare", "Caseifici, cantine, lavorazione del pesce", "Ricambi di microgriglie e setacci statici, cestelli dei pozzetti, pale degli sgrassatori: pezzi piccoli di macchine che il costruttore non segue più.", "non per contatto con l'alimento"),
        ("Acque meteoriche", "Caditoie, sfioratori", "Cestelli e griglie per caditoie fuori standard, schermi degli scarichi, a moduli che si agganciano.", "cestelli grandi: a moduli"),
        ("Impianti pilota e ricerca", "Università, società di ingegneria", "Supporti per biofilm a geometria gyroid, piccoli rotostacci, portadiffusori: il prototipo che poi diventa serie.", "costo al litro in grande serie"),
    ],
    # ---------------------------------------------------------------- p6
    "p6_head": "Materiale, limiti e contatti",
    "s05": "Il materiale", "s05_note": "Polipropilene SAF · DPG-MAT-PP",
    "props": [("Resistenza a trazione", "30 MPa"), ("Modulo elastico", "1600 MPa"), ("Allungamento a rottura", "20%"),
              ("Inflessione sotto carico, 0,45 MPa", "100 °C"), ("Densità", "circa 0,9 g/cm³"),
              ("A tenuta d'acqua", "da 1 mm di parete")],
    "props_note": "Valori di scheda del produttore della polvere, su provini. Il pezzo si valuta sul pezzo.",
    "chem": [("Acidi diluiti non ossidanti", "solforico, cloridrico", "ok"),
             ("Basi", "soda caustica", "ok"),
             ("Coagulanti", "cloruro ferrico", "ok"),
             ("Perossido di idrogeno", "a temperatura ambiente", "ok"),
             ("Ipoclorito di sodio", "a freddo sì, caldo ed esposizione continua da valutare", "cond"),
             ("Polielettroliti, PAC, H₂S, metanolo, acido peracetico", "da verificare sul vostro fluido", "cond"),
             ("Ozono, biossido di cloro", "degradano il PP: serve PVDF", "no"),
             ("Acidi ossidanti concentrati, solventi aromatici e clorurati", "attaccano o gonfiano il PP", "no")],
    "chem_key": ("adatto", "con condizioni", "no", "dati del polimero di base: su richiesta proviamo il pezzo nel vostro fluido."),
    "s06": "Materiali per il settore",
    "mat_head": ("Materiale", "Processo", "Perché qui", "Riferimento"),
    "mat": [("Polipropilene", "SAF", "il materiale dell'acqua: non assorbe acqua, non idrolizza, regge la chimica di processo; UL94 HB, non per requisiti al fuoco", "DPG-MAT-PP"),
            ("PA2200 (PA12)", "SLS", "dove serve più rigidità o temperatura, fino a +80 °C sotto carico, fuori dall'immersione continua: la poliammide assorbe acqua", "DPG-MAT-PA2200")],
    "s07": "Il rovescio", "s07_note": "Quando non conviene, ve lo diciamo prima",
    "rov": [("Sotto 2 mm di luce", "la fessura fine della filtrazione a sabbia resta a wedge-wire e tela."),
            ("Oltre 30 cm", "il pezzo si divide in moduli; tubi, lastre e deflettori grandi non sono il nostro mestiere."),
            ("Acqua potabile", "il nostro PP non ha certificazioni per l'acqua destinata al consumo umano."),
            ("Ozono e biossido di cloro", "il PP non li regge: in quello stadio va il PVDF."),
            ("Sabbia e grit", "a monte della dissabbiatura poliuretano e UHMW durano di più."),
            ("Pressione nel tempo", "non dichiariamo una pressione nominale: si prova sul vostro caso."),
            ("Freddo e sole", "sotto 0 °C il PP diventa fragile agli urti; all'aperto la tenuta ai raggi UV si valuta.")],
    "needs_k": "Per un'offerta ci servono",
    "needs": ["Il pezzo vecchio, anche rotto, oppure disegno o STEP", "Due foto del pezzo montato",
              "Il fluido, la chimica e la temperatura di esercizio", "Quanti pezzi: oggi, e all'anno"],
    "cta": ("Mandateci il pezzo che non trovate più.", "Vi diciamo anche quando non conviene."),
    "art": {},  # usa le etichette italiane di h2o_art.LBL
}

FR = {
    "html_lang": "fr", "code": "FR", "file": "DPG_Settore_H2O_FR",
    "sheet": "Fiche secteur", "rev": "REV. 02 · PROJET",
    "tb": ("Document", "Révision", "Langue", "Éditeur", "Page"),
    "eyebrow1": "Eaux usées, eau industrielle, aquaculture",
    "h1": ("Tamis, filtres et pièces", "en polypropylène, sans moule"), "h1_size": "35pt",
    "lead": "Panneaux perforés, éléments de dégrilleur, buses, crépines et les pièces plastiques que le constructeur ne "
            "fait plus : en <strong>polypropylène fritté</strong>, sur plan ou à partir de l'ancienne pièce, de une à "
            "quelques milliers. Le matériau que l'épuration utilise depuis toujours, avec une géométrie que le moule ne "
            "permet pas.",
    "kpis": [("≥ 2", "mm", "passage, trous et fentes"), ("≤ 30", "cm", "pièce unique, au-delà en modules"),
             ("0", "moule", "de la pièce unique à la série")],
    "fig1": "Panneaux de tamis à bande, vue isométrique",
    "legend1": "Modules perforés clipsés sur le châssis inox du tamis. En bleu : l'eau",
    "key_red": "<b>En rouge</b> : les pièces produites en fabrication additive",
    "p2_head": "Traitement des eaux usées et de l'eau industrielle",
    "s01": "Pourquoi maintenant",
    "stats": [
        ("2024/3019", "Directive UE eaux résiduaires urbaines",
         "Transposition avant juillet 2027. Traitement des micropolluants obligatoire au-delà de 150 000 EH : "
         "20 % des stations en 2033, 60 % en 2039, toutes en 2045."),
        ("≥ 80 %", "Payé par les producteurs",
         "Responsabilité élargie : l'industrie pharmaceutique et cosmétique finance au moins 80 % du traitement "
         "quaternaire. De nouvelles étapes, de nouveaux filtres."),
        ("Marchés", "Les pièces de rechange s'achètent par appel d'offres",
         "Thames Water a un accord-cadre pour les dégrilleurs de toutes marques ; au Portugal, SIMARSUL met en "
         "concurrence les pièces des tamis marque par marque."),
    ],
    "s02": "Le compte que vous connaissez",
    "was_k": "Aujourd'hui",
    "was": "Le panneau du tamis se commande au constructeur et arrive en quelques semaines, si le modèle est encore au "
           "catalogue. La buse du filtre est d'une marque qui n'existe plus. La crépine est un assemblage collé qui fuit "
           "là où il ne faut pas, et la tôle perforée inox pèse, coûte et demande un outillage même pour une petite variante.",
    "now_k": "En frittage",
    "now": "L'ancienne pièce devient un fichier avec sa révision, et le fichier un lot : d'une pièce à quelques milliers, "
           "sans moule. Châssis, clips, nervures et filetage naissent dans la même pièce. Le trou peut s'élargir vers la "
           "sortie pour ne rien retenir, et la fois suivante le réassort est identique.",
    "s03": "Le polypropylène imprimé est déjà en station", "s03_note": "Sources publiques, en bas de page",
    "evidence": [
        ("Exploitant, Royaume-Uni", "United Utilities",
         "Dans le programme Printfrastructure, financé par l'Ofwat, il utilise tous les jours des pièces polymères "
         "imprimées : buses de lavage, goulottes pour instruments et pièces de rechange introuvables pour les bras de filtres."),
        ("Constructeur de tamis", "Johnson Screens",
         "A remplacé l'acier inox par du polypropylène imprimé pour les éléments de la bande filtrante d'un dégrilleur "
         "d'entrée d'eaux usées."),
        ("Exploitant, Royaume-Uni", "Anglian Water",
         "La première pièce imprimée en essai, avec l'Université de Sheffield, a été une buse de filtre."),
        ("Recherche, 2026", "Supports MBBR en PP",
         "Supports de biofilm à géométrie gyroïde imprimés en PP, testés sur eaux usées domestiques en pilote "
         "(Processes, 2026)."),
    ],
    "case_k": "En production, aujourd'hui",
    "case": "Pour un groupe international du traitement de l'eau, nous produisons en série récurrente des <strong>panneaux "
            "filtrants en polypropylène fritté, passage de 2 mm</strong> : réassort depuis le stock numérique, lot tracé. "
            "<strong>Pas un prototype : une fourniture.</strong>",
    "why_k": "Pourquoi le polypropylène",
    "why": "Il n'absorbe pas l'eau et ne s'hydrolyse pas, contrairement au polyamide. Il résiste aux acides et bases "
           "dilués, à la soude, au chlorure ferrique et à la chimie de lavage. Il flotte (environ 0,9 g/cm³) et pèse "
           "environ un huitième de l'inox. C'est le matériau des cuves, tuyaux et buses depuis toujours.",
    "fonti_k": "Sources",
    "fonti": [
        "Directive (UE) 2024/3019, eur-lex.europa.eu",
        "Hydro International, Thames Water screen services framework, hydro-int.com",
        "SIMARSUL, avis TED 056207-2024",
        "United Utilities, « Printfrastructure », unitedutilities.com",
        "Johnson Screens et HP, johnsonscreens.com ; 3dprint.com, 2022",
        "Anglian Water et Univ. de Sheffield, 3dprint.com, 2015",
        "Processes 14(6):1001, 2026, doi 10.3390/pr14061001",
        "Stratasys, SAF PP : fiche matière et livre blanc sur l'étanchéité",
        "Résistance chimique du PP : Braskem, INEOS, Charlotte Pipe",
    ],
    "p3_head": "Où nous entrons dans la station",
    "eyebrow3": "Plan de la station",
    "h2_map": "Du dégrillage aux boues : dix points où la pièce en PP imprimé a du sens",
    "fig2": "Schéma d'une station à boues activées",
    "legend3": "En bleu l'eau, en pointillé l'air et la ligne boues. Pertinence : haute = pièce déjà en plastique, spécifique, rechange difficile",
    "key3": "<b>En rouge</b> : là où entre le PP imprimé",
    "fit": {"A": "haute", "M": "moyenne"},
    "map": [
        ("Panneaux et éléments de dégrilleur", "Tamis à bande, dégrilleurs à peigne, tamis rotatifs : panneaux perforés de 2 mm, éléments, guides, patins, porte-brosses.", "A"),
        ("Petites pièces des racleurs", "Entretoises, cales, embouts de racleurs d'écume, brides de réglage des déversoirs.", "A"),
        ("Dosage des réactifs", "Petits mélangeurs statiques, crépines d'aspiration, cannes d'injection pour chlorure ferrique et hypochlorite, basse pression.", "M"),
        ("Aération", "Selles, bagues, adaptateurs et raccords pour grilles de diffuseurs qui ne sont plus fabriquées. Le diffuseur reste de série.", "M"),
        ("Grilles de rétention MBBR", "Modules à fentes de 4–5 mm au profil anti-coincement, pour petites stations, industrie, pilotes.", "A"),
        ("Supports de sondes", "Cages, porte-sondes pendulaires, capots avec buse d'air de nettoyage intégrée à la pièce.", "A"),
        ("Buses et crépines", "Deuxième source pour les modèles hors catalogue : biofiltres, drainages, échange d'ions. Fente de 2 mm.", "A"),
        ("Désodorisation", "Distributeurs de liquide et collecteurs avec les buses dans la même pièce, supports, dévésiculeurs.", "M"),
        ("Ligne boues", "Porte-buses de lavage, supports de lames, déflecteurs de filtres à bandes et d'épaississeurs.", "M"),
        ("Instrumentation", "Puits de tranquillisation, crépines d'échantillonneur, supports dans toute la station.", "A"),
    ],
    "off_k": "Hors champ, et nous le disons avant",
    "off": ["contact avec l'ozone et le dioxyde de chlore", "roues de pompes et centrifugeuses", "grands déflecteurs et déversoirs en PRV",
            "supports MBBR et garnissages de série", "fentes fines des filtres à sable, sous 2 mm", "zones Atex du biogaz"],
    "p4_head": "Trois portes d'entrée",
    "d1_small": "Pour exploitants, mainteneurs et sociétés de service sur dégrilleurs",
    "d1_h": "La pièce plastique qu'on ne trouve plus.",
    "d1_lead": "Panneaux, éléments et guides de tamis à bande et de dégrilleurs à peigne, tamis rotatifs, capots, patins, "
               "porte-brosses et porte-buses : nous les refaisons en PP à partir de l'ancienne pièce, même pour des "
               "machines qui ne sont plus fabriquées, même à l'unité. Pour qui fait du service multimarque, nous sommes le "
               "fournisseur des pièces que le constructeur ne livre plus, ou livre en plusieurs semaines.",
    "steps": [("old", "L'ancienne pièce", "ou le plan, ou le STEP. Même cassée, même d'une marque disparue."),
              ("scan", "Relevé 3D", "nous mesurons la pièce et reconstruisons cotes, filetages et ajustements."),
              ("file", "Fichier révisé", "la pièce de rechange devient votre référence, avec sa révision."),
              ("batch", "Lot en PP", "d'une pièce à quelques milliers, tracé, sans moule."),
              ("again", "Réassort identique", "dans un an ou dans dix, depuis le fichier, sans étagère.")],
    "d2_small": "Pour constructeurs de dégrilleurs, tamis et filtres",
    "d2_h": "Le panneau perforé en plastique, à la place de la tôle.",
    "fig3": "Coupe du panneau",
    "fig3_cap": "Dans la tôle, le trou est droit. Imprimé, il peut s'élargir vers la sortie comme un fil profilé : ce qui entre, passe.",
    "fig4": "Surface ouverte, trous de 2 mm en quinconce",
    "fig4_cap": "Calcul géométrique. L'entraxe minimal se fixe avec vous, selon la rigidité dont le panneau a besoin.",
    "cmp_head": ("Tôle inox perforée", "Panneau injecté", "PP fritté"),
    "cmp": [("Outillage", "poinçonnage ou laser", "un moule par format", "aucun : le fichier"),
            ("Lot pertinent", "dès une pièce", "des milliers", "d'une pièce à quelques milliers"),
            ("Forme du trou", "droite", "celle qui se démoule", "droite, conique, différente par zone"),
            ("Châssis et clips", "soudés ou vissés", "dans le moule", "dans la pièce, même pour une seule rechange"),
            ("Poids", "7,9 g/cm³", "léger", "environ 0,9 g/cm³"),
            ("Chlorures, eau de mer", "l'inox en souffre", "aucun problème", "aucun problème"),
            ("Sable et grit", "bonne", "excellente en polyuréthane", "moyenne : en aval du dessablage"),
            ("Passage minimal", "sous le millimètre", "fin", "2 mm")],
    "ticks4": [("Châssis, nervures, clips et logement de joint", " dans la même pièce : le module se clipse et se change seul."),
               ("Passage différent par zone", " sur le même panneau, et référence gravée sur le châssis."),
               ("Un huitième du poids de l'inox", " : le changement de panneaux se fait à la main, sans palan."),
               ("Modules jusqu'à 30 cm", " de côté. Au-delà, le panneau se divise en modules clipsés, comme les panneaux polyuréthane des cribles."),
               ("Là où ça ne va pas", " : sable et grit avant le dessablage usent le PP plus vite que le polyuréthane et l'UHMW ; sous 2 mm, fil profilé et toile restent la réponse.")],
    "p5_head": "Trois portes d'entrée, et au-delà",
    "d3_small": "Pour qui fabrique, vend ou monte des buses et crépines",
    "d3_h": "Buses et crépines : la deuxième source.",
    "fig5": "Crépine de rétrolavage : corps, fentes et filetage en une pièce. À droite, coupe A-A.",
    "nz_p": "Le modèle hors catalogue, la marque qui n'existe plus, la variante pour une seule station : nous la faisons en "
            "PP, à partir de la pièce ou du plan, avec le même filetage.",
    "ticks5": [("Corps, fentes et filetage en une pièce", " : aucun collage, aucune jonction qui fuit."),
               ("Fente en V", " élargie vers l'intérieur : elle se nettoie au rétrolavage."),
               ("Le trou d'air de lavage", " dans la tige, dans la même pièce, si votre buse le prévoit."),
               ("Fente à partir de 2 mm", " : biofiltres, drainages sur gravier, échange d'ions, aquaculture. Pour le sable fin, "
                "nous imprimons le corps et la tête fendue reste de catalogue.")],
    "s04": "Des idées au-delà du dégrillage", "s04_note": "Là où le même PP travaille déjà", "lim": "limite",
    "ideas": [
        ("Supports de sondes autonettoyants", "Toutes les stations", "Cages et capots pour sondes d'oxygène, de pH et de turbidité, avec le canal d'air de nettoyage dans la pièce.", "charges faibles, pièces spécifiques"),
        ("Grilles de rétention MBBR", "Stations compactes, industrie, pilotes", "Modules plans à la place du cylindre en fil profilé inox, fentes de 4–5 mm, profil qui ne coince pas le support.", "grandes stations : en modules"),
        ("Distributeurs de tours de lavage", "Désodorisation", "Distributeur de liquide et buses en une seule pièce, sans soudure, dans la chimie de lavage du PP : soude, hypochlorite, acide sulfurique.", "grands dévésiculeurs : en modules"),
        ("Rechanges de filtres à disques et à tambour", "Tertiaire, aquaculture", "Buses et rampes de lavage, patins d'aspiration, cadres de panneaux : la toile reste toile, le support s'imprime.", "la toile sous 2 mm ne s'imprime pas"),
        ("Aquaculture en recirculation", "RAS, écloseries", "Grilles de sortie des bassins au passage adapté à la taille du poisson, plaques de distribution des dégazeurs, porte-buses. En eau de mer, l'inox souffre, le PP non.", "UV en extérieur à évaluer"),
        ("Galvanoplastie et eaux industrielles", "Prétraitement", "Rampes, mélangeurs et internes des cuves de neutralisation, là où le PP est déjà le matériau de la maison.", "pas de solvants aromatiques ni chlorés"),
        ("Tours de refroidissement", "Eau de process", "Buses de pulvérisation et adaptateurs pour des tours dont les pièces ne se trouvent plus, avec l'orifice qu'il faut.", "au-delà d'environ 60 °C à évaluer"),
        ("Industrie agroalimentaire", "Fromageries, caves, transformation du poisson", "Pièces de microtamis et de tamis statiques, paniers de regards, pales de dégraisseurs : les petites pièces de machines que le constructeur ne suit plus.", "pas de contact avec l'aliment"),
        ("Eaux pluviales", "Avaloirs, déversoirs d'orage", "Paniers et grilles pour avaloirs hors standard, écrans de sorties, en modules clipsés.", "grands paniers : en modules"),
        ("Pilotes et recherche", "Universités, bureaux d'études", "Supports de biofilm gyroïdes, petits tamis rotatifs, porte-diffuseurs : le prototype qui devient série.", "coût au litre en grande série"),
    ],
    "p6_head": "Matériau, limites et contacts",
    "s05": "Le matériau", "s05_note": "Polypropylène SAF · DPG-MAT-PP",
    "props": [("Résistance à la traction", "30 MPa"), ("Module d'élasticité", "1600 MPa"), ("Allongement à la rupture", "20 %"),
              ("Fléchissement sous charge, 0,45 MPa", "100 °C"), ("Densité", "environ 0,9 g/cm³"),
              ("Étanche à l'eau", "dès 1 mm de paroi")],
    "props_note": "Valeurs de la fiche du fabricant de la poudre, sur éprouvettes. La pièce s'évalue sur la pièce.",
    "chem": [("Acides dilués non oxydants", "sulfurique, chlorhydrique", "ok"),
             ("Bases", "soude caustique", "ok"),
             ("Coagulants", "chlorure ferrique", "ok"),
             ("Peroxyde d'hydrogène", "à température ambiante", "ok"),
             ("Hypochlorite de sodium", "à froid oui ; à chaud et en exposition continue, à évaluer", "cond"),
             ("Polyélectrolytes, PAC, H₂S, méthanol, acide peracétique", "à vérifier sur votre fluide", "cond"),
             ("Ozone, dioxyde de chlore", "dégradent le PP : il faut du PVDF", "no"),
             ("Acides oxydants concentrés, solvants aromatiques et chlorés", "attaquent ou font gonfler le PP", "no")],
    "chem_key": ("adapté", "sous conditions", "non", "données du polymère de base : sur demande, nous testons la pièce dans votre fluide."),
    "s06": "Matériaux du secteur",
    "mat_head": ("Matériau", "Procédé", "Pourquoi ici", "Référence"),
    "mat": [("Polypropylène", "SAF", "le matériau de l'eau : n'absorbe pas l'eau, ne s'hydrolyse pas, résiste à la chimie de process ; UL94 HB, pas pour les exigences feu", "DPG-MAT-PP"),
            ("PA2200 (PA12)", "SLS", "quand il faut plus de rigidité ou de température, jusqu'à +80 °C sous charge, hors immersion continue : le polyamide absorbe l'eau", "DPG-MAT-PA2200")],
    "s07": "Le revers", "s07_note": "Quand ça ne vaut pas la peine, nous le disons avant",
    "rov": [("Sous 2 mm de passage", "la fente fine de la filtration sur sable reste au fil profilé et à la toile."),
            ("Au-delà de 30 cm", "la pièce se divise en modules ; tubes, plaques et grands déflecteurs ne sont pas notre métier."),
            ("Eau potable", "notre PP n'a pas de certification pour l'eau destinée à la consommation humaine."),
            ("Ozone et dioxyde de chlore", "le PP ne les supporte pas : à cette étape, c'est le PVDF."),
            ("Sable et grit", "en amont du dessablage, polyuréthane et UHMW durent plus longtemps."),
            ("Pression dans le temps", "nous ne déclarons pas de pression nominale : on l'essaie sur votre cas."),
            ("Froid et soleil", "sous 0 °C, le PP devient fragile aux chocs ; en extérieur, la tenue aux UV s'évalue.")],
    "needs_k": "Pour une offre, il nous faut",
    "needs": ["L'ancienne pièce, même cassée, ou le plan ou le STEP", "Deux photos de la pièce montée",
              "Le fluide, la chimie et la température de service", "Combien de pièces : aujourd'hui, et par an"],
    "cta": ("Envoyez-nous la pièce que vous ne trouvez plus.", "Nous dirons aussi quand c'est non."),
    "art": {
        "c_hole": "Trous de 2 mm en quinconce, même coniques", "c_module": "Module remplaçable seul",
        "c_clip": "Clips imprimés dans la pièce", "c_frame": "Châssis et nervure en une pièce",
        "lift": "Relevage", "screen": "Dégrillage", "grit": "Dessablage", "prim": "Décantation I",
        "dose": "Dosage", "bio": "Biologique · MBBR", "sec": "Clarification", "filt": "Filtration",
        "dis": "Désinfection", "dis_off": "UV / ozone : hors champ", "odour": "Désodorisation",
        "thick": "Épaississement", "dewat": "Déshydratation", "dig": "Digestion", "dig_off": "Atex : hors champ",
        "sludge": "Ligne boues",
        "h_straight": "TROU DROIT, POINÇONNÉ", "h_conical": "TROU CONIQUE, IMPRIMÉ",
        "h_stuck": "se coince à mi-épaisseur", "h_pass": "passe, ou reste dessus et le lavage la décolle",
        "flow": "FLUX", "pitch": "entraxe", "web": "voile", "plate": "TÔLE PERFORÉE COURANTE 30–45 %", "dec": ",",
    },
}

EN = {
    "html_lang": "en", "code": "EN", "file": "DPG_Settore_H2O_EN",
    "sheet": "Sector sheet", "rev": "REV. 02 · DRAFT",
    "tb": ("Document", "Revision", "Language", "Publisher", "Page"),
    "eyebrow1": "Wastewater, industrial water, aquaculture",
    "h1": ("Screens, filters and spares", "in polypropylene, without a mould"), "h1_size": "33pt",
    "lead": "Perforated panels, screen elements, nozzles, strainers and the plastic parts the maker no longer supplies: "
            "in <strong>sintered polypropylene</strong>, from the drawing or from the old part, from one to a few "
            "thousand. The material wastewater treatment has always used, in a geometry a mould cannot make.",
    "kpis": [("≥ 2", "mm", "aperture, holes and slots"), ("≤ 30", "cm", "single part, modules beyond"),
             ("0", "moulds", "from one part to a series")],
    "fig1": "Band screen panels, isometric view",
    "legend1": "Perforated modules clipped to the stainless frame of the screen. In blue: the water",
    "key_red": "<b>In red</b>: the parts made by additive manufacturing",
    "p2_head": "Wastewater and industrial water treatment",
    "s01": "Why now",
    "stats": [
        ("2024/3019", "EU Urban Wastewater Treatment Directive",
         "Transposition by July 2027. Micropollutant (quaternary) treatment mandatory above 150,000 p.e.: "
         "20% of plants by 2033, 60% by 2039, all of them by 2045."),
        ("≥ 80%", "Paid by producers",
         "Extended producer responsibility: the pharmaceutical and cosmetics industries fund at least 80% of "
         "quaternary treatment. New stages, new filters."),
        ("Frameworks", "Spares are bought by tender",
         "Thames Water runs a screen services framework covering all makes; in Portugal, SIMARSUL tenders "
         "screen spare parts brand by brand."),
    ],
    "s02": "The sums you already know",
    "was_k": "Today",
    "was": "The screen panel is ordered from the maker and arrives in weeks, if the model is still in the catalogue. "
           "The filter nozzle is from a brand that no longer exists. The strainer is a glued assembly that leaks where "
           "it should not, and stainless perforated plate is heavy, costly and needs tooling even for a small variant.",
    "now_k": "Sintered",
    "now": "The old part becomes a file with its revision, and the file becomes a batch: from one part to a few "
           "thousand, without a mould. Frame, clips, ribs and thread are born in the same part. The hole can widen "
           "towards the outlet so it does not hold, and next time the reorder is identical.",
    "s03": "Printed polypropylene is already in the plant", "s03_note": "Public sources, at the foot of the page",
    "evidence": [
        ("Water utility, United Kingdom", "United Utilities",
         "In its Ofwat-funded Printfrastructure programme it uses printed polymer parts every day: jetting nozzles, "
         "instrument troughs and obsolete spares for filter arms."),
        ("Screen manufacturer", "Johnson Screens",
         "Moved the elements of the filtration belt of a wastewater inlet screen from stainless steel to printed "
         "polypropylene."),
        ("Water utility, United Kingdom", "Anglian Water",
         "The first part it trialled printing, with the University of Sheffield, was a filter nozzle."),
        ("Research, 2026", "PP MBBR carriers",
         "Gyroid biofilm carriers printed in PP, tested on domestic wastewater at pilot scale (Processes, 2026)."),
    ],
    "case_k": "In production today",
    "case": "For an international water treatment group we produce, as a recurring series, <strong>sintered "
            "polypropylene filter panels with a 2 mm aperture</strong>: reordered from a digital warehouse, batch traced. "
            "<strong>Not a prototype: a supply.</strong>",
    "why_k": "Why polypropylene",
    "why": "It does not absorb water and does not hydrolyse, unlike polyamide. It withstands dilute acids and bases, "
           "caustic soda, ferric chloride and cleaning chemicals. It floats (about 0.9 g/cm³) and weighs about an eighth "
           "of stainless steel. It is what tanks, pipes and nozzles have always been made of.",
    "fonti_k": "Sources",
    "fonti": [
        "Directive (EU) 2024/3019, eur-lex.europa.eu",
        "Hydro International, Thames Water screen services framework, hydro-int.com",
        "SIMARSUL, TED notice 056207-2024",
        "United Utilities, “Printfrastructure”, unitedutilities.com",
        "Johnson Screens and HP, johnsonscreens.com; 3dprint.com, 2022",
        "Anglian Water and Univ. of Sheffield, 3dprint.com, 2015",
        "Processes 14(6):1001, 2026, doi 10.3390/pr14061001",
        "Stratasys, SAF PP: material datasheet and watertightness white paper",
        "PP chemical resistance: Braskem, INEOS, Charlotte Pipe",
    ],
    "p3_head": "Where we fit in the plant",
    "eyebrow3": "Plant map",
    "h2_map": "From the screens to the sludge: ten places where a printed PP part makes sense",
    "fig2": "Layout of an activated sludge plant",
    "legend3": "In blue the water, dashed the air and the sludge line. Fit: high = part already in plastic, plant-specific, hard to source",
    "key3": "<b>In red</b>: where printed PP comes in",
    "fit": {"A": "high", "M": "medium"},
    "map": [
        ("Screen panels and elements", "Band screens, rake-comb screens, drum screens: 2 mm perforated panels, elements, guides, wear shoes, brush holders.", "A"),
        ("Scraper small parts", "Spacers, filler blocks, scum skimmer tips, weir adjustment brackets.", "A"),
        ("Chemical dosing", "Small static mixers, foot-valve strainers, injection tips for ferric chloride and hypochlorite, low pressure.", "M"),
        ("Aeration", "Saddles, rings, adapters and fittings for diffuser grids no longer made. The diffuser itself stays standard.", "M"),
        ("MBBR retention sieves", "Modules with 4–5 mm slots and an anti-wedging profile, for small, industrial and pilot plants.", "A"),
        ("Probe holders", "Cages, pendulum probe holders, shrouds with the air-cleaning nozzle built into the part.", "A"),
        ("Nozzles and strainers", "Second source for off-catalogue models: biofilters, underdrains, ion exchange. 2 mm slots.", "A"),
        ("Odour control", "Liquid distributors and headers with the nozzles in the same part, supports, mist eliminators.", "M"),
        ("Sludge line", "Wash-nozzle holders, blade holders, chicanes for belt presses and thickeners.", "M"),
        ("Instrumentation", "Stilling wells, sampler strainers, brackets across the whole plant.", "A"),
    ],
    "off_k": "Out of scope, and we say so first",
    "off": ["contact with ozone and chlorine dioxide", "pump impellers and centrifuges", "large GRP baffles and weirs",
            "standard MBBR carriers and packing", "fine sand-filter slots below 2 mm", "Atex zones of the biogas line"],
    "p4_head": "Three ways in",
    "d1_small": "For utilities, maintenance teams and screen service companies",
    "d1_h": "The plastic spare you can no longer find.",
    "d1_lead": "Panels, elements and guides of band and rake-comb screens, drum screens, covers, wear shoes, brush holders "
               "and nozzle holders: we remake them in PP from the old part, also for machines no longer built, and also "
               "a single piece. For multi-brand service companies we are the supplier of the parts the maker no longer "
               "supplies, or supplies in weeks.",
    "steps": [("old", "The old part", "or the drawing, or the STEP. Even broken, even from a brand that is gone."),
              ("scan", "3D survey", "we measure the part and rebuild dimensions, threads and fits."),
              ("file", "Revised file", "the spare becomes your own part number, with its revision."),
              ("batch", "PP batch", "from one part to a few thousand, traced, without a mould."),
              ("again", "Identical reorder", "in one year or in ten, from the file, with no shelf.")],
    "d2_small": "For makers of screens, drum screens and filters",
    "d2_h": "The perforated panel in plastic, instead of the plate.",
    "fig3": "Panel cross-section",
    "fig3_cap": "In plate, the hole is straight. Printed, it can widen towards the outlet like a wedge-wire profile: what goes in, goes through.",
    "fig4": "Open area, 2 mm holes, staggered",
    "fig4_cap": "Geometric calculation. The minimum web is set with you, on the stiffness the panel needs.",
    "cmp_head": ("Perforated stainless plate", "Injection-moulded panel", "Sintered PP"),
    "cmp": [("Tooling", "punching or laser", "one mould per format", "none: the file"),
            ("Sensible batch", "from one part", "thousands", "from one part to a few thousand"),
            ("Hole shape", "straight", "whatever can be demoulded", "straight, tapered, varied by zone"),
            ("Frame and clips", "welded or bolted", "in the mould", "in the part, even for a single spare"),
            ("Weight", "7.9 g/cm³", "light", "about 0.9 g/cm³"),
            ("Chlorides, seawater", "stainless suffers", "no problem", "no problem"),
            ("Sand and grit", "good", "excellent in polyurethane", "fair: downstream of grit removal"),
            ("Minimum aperture", "below one millimetre", "fine", "2 mm")],
    "ticks4": [("Frame, ribs, clips and gasket seat", " in the same part: the module clips in and is replaced on its own."),
               ("Different apertures by zone", " on the same panel, and the part number engraved on the frame."),
               ("An eighth of the weight of stainless", ": panels are changed by hand, without a hoist."),
               ("Modules up to 30 cm", " a side. Beyond that, the panel is split into modules that clip together, like the polyurethane panels of vibrating screens."),
               ("Where it does not fit", ": sand and grit upstream of grit removal wear PP faster than polyurethane and UHMW; below 2 mm, wedge wire and cloth remain the answer.")],
    "p5_head": "Three ways in, and beyond",
    "d3_small": "For those who make, sell or fit nozzles and strainers",
    "d3_h": "Nozzles and strainers: the second source.",
    "fig5": "Backwash strainer: body, slots and thread in one part. Right, section A-A.",
    "nz_p": "The off-catalogue model, the brand that no longer exists, the variant for a single plant: we make it in PP, "
            "from the part or the drawing, with the same thread.",
    "ticks5": [("Body, slots and thread in one part", ": no gluing, no joint to leak."),
               ("Wedge-shaped slot", " widening inwards: it cleans itself at backwash."),
               ("The air-scour hole", " in the stem, in the same part, if your nozzle has one."),
               ("Slots from 2 mm", ": biofilters, gravel underdrains, ion exchange, aquaculture. For fine sand we print the "
                "body and the slotted cap stays off the shelf.")],
    "s04": "Ideas beyond the screen", "s04_note": "Where the same PP already works", "lim": "limit",
    "ideas": [
        ("Self-cleaning probe holders", "Every plant", "Cages and shrouds for oxygen, pH and turbidity probes, with the air-cleaning channel inside the part.", "low loads, plant-specific parts"),
        ("MBBR retention sieves", "Compact plants, industry, pilots", "Flat modules instead of the stainless wedge-wire cylinder, 4–5 mm slots, a profile that does not wedge the carrier.", "large plants: in modules"),
        ("Scrubber distributors", "Odour control", "Liquid distributor and nozzles in one part, no welds, in PP's own scrubbing chemistry: caustic, hypochlorite, sulphuric acid.", "large eliminators: in modules"),
        ("Disc and drum filter spares", "Tertiary, aquaculture", "Wash nozzles and spray bars, suction shoes, panel frames: the cloth stays cloth, the support is printed.", "cloth below 2 mm cannot be printed"),
        ("Recirculating aquaculture", "RAS, hatcheries", "Tank outlet screens sized to the fish, degasser distribution plates, nozzle holders. In seawater stainless suffers, PP does not.", "outdoor UV to be assessed"),
        ("Plating and industrial water", "Pre-treatment", "Spargers, mixers and internals of neutralisation tanks, where PP is already the house material.", "no aromatic or chlorinated solvents"),
        ("Cooling towers", "Process water", "Spray nozzles and adapters for towers whose spares can no longer be found, with the orifice you need.", "above about 60 °C to be assessed"),
        ("Food industry", "Dairies, wineries, fish processing", "Spares for micro-screens and static sieves, gully baskets, grease-trap paddles: small parts of machines the maker no longer supports.", "not for food contact"),
        ("Stormwater", "Gullies, overflows", "Baskets and screens for non-standard gullies, outfall screens, in modules that clip together.", "large baskets: in modules"),
        ("Pilot plants and research", "Universities, engineering firms", "Gyroid biofilm carriers, small drum screens, diffuser holders: the prototype that becomes a series.", "cost per litre at full scale"),
    ],
    "p6_head": "Material, limits and contacts",
    "s05": "The material", "s05_note": "SAF polypropylene · DPG-MAT-PP",
    "props": [("Tensile strength", "30 MPa"), ("Tensile modulus", "1600 MPa"), ("Elongation at break", "20%"),
              ("Heat deflection, 0.45 MPa", "100 °C"), ("Density", "about 0.9 g/cm³"),
              ("Watertight", "from 1 mm wall")],
    "props_note": "Datasheet values from the powder maker, on test specimens. The part is assessed on the part.",
    "chem": [("Dilute non-oxidising acids", "sulphuric, hydrochloric", "ok"),
             ("Bases", "caustic soda", "ok"),
             ("Coagulants", "ferric chloride", "ok"),
             ("Hydrogen peroxide", "at room temperature", "ok"),
             ("Sodium hypochlorite", "cold yes; hot and continuous exposure to be assessed", "cond"),
             ("Polyelectrolytes, PAC, H₂S, methanol, peracetic acid", "to be checked in your fluid", "cond"),
             ("Ozone, chlorine dioxide", "degrade PP: PVDF is needed", "no"),
             ("Concentrated oxidising acids, aromatic and chlorinated solvents", "attack or swell PP", "no")],
    "chem_key": ("suitable", "with conditions", "no", "base-polymer data: on request we test the part in your fluid."),
    "s06": "Materials for the sector",
    "mat_head": ("Material", "Process", "Why here", "Reference"),
    "mat": [("Polypropylene", "SAF", "the water material: does not absorb water, does not hydrolyse, withstands process chemistry; UL94 HB, not for fire requirements", "DPG-MAT-PP"),
            ("PA2200 (PA12)", "SLS", "where more stiffness or temperature is needed, up to +80 °C under load, out of continuous immersion: polyamide absorbs water", "DPG-MAT-PA2200")],
    "s07": "The flip side", "s07_note": "When it does not pay, we tell you first",
    "rov": [("Below 2 mm aperture", "the fine slot of sand filtration stays with wedge wire and cloth."),
            ("Beyond 30 cm", "the part is split into modules; pipes, sheets and large baffles are not our trade."),
            ("Drinking water", "our PP holds no approval for water intended for human consumption."),
            ("Ozone and chlorine dioxide", "PP does not withstand them: that stage needs PVDF."),
            ("Sand and grit", "upstream of grit removal, polyurethane and UHMW last longer."),
            ("Pressure over time", "we do not state a pressure rating: it is tested on your case."),
            ("Cold and sun", "below 0 °C PP becomes brittle on impact; outdoors, UV resistance is assessed.")],
    "needs_k": "For a quote we need",
    "needs": ["The old part, even broken, or the drawing or STEP", "Two photos of the part in place",
              "The fluid, the chemistry and the operating temperature", "How many parts: now, and per year"],
    "cta": ("Send us the part you can no longer find.", "We also tell you when it does not pay."),
    "art": {
        "c_hole": "2 mm holes, staggered, also tapered", "c_module": "Module replaceable on its own",
        "c_clip": "Clips printed in the part", "c_frame": "Frame and rib in one part",
        "lift": "Pumping", "screen": "Screening", "grit": "Grit removal", "prim": "Primary settling",
        "dose": "Dosing", "bio": "Biological · MBBR", "sec": "Final settling", "filt": "Filtration",
        "dis": "Disinfection", "dis_off": "UV / ozone: out of scope", "odour": "Odour control",
        "thick": "Thickening", "dewat": "Dewatering", "dig": "Digestion", "dig_off": "Atex: out of scope",
        "sludge": "Sludge line",
        "h_straight": "STRAIGHT HOLE, PUNCHED", "h_conical": "TAPERED HOLE, PRINTED",
        "h_stuck": "wedges halfway through", "h_pass": "goes through, or sits on top and the wash lifts it",
        "flow": "FLOW", "pitch": "pitch", "web": "web", "plate": "TYPICAL PERFORATED PLATE 30–45%", "dec": ".",
    },
}

LANGS = {"it": IT, "fr": FR, "en": EN}
